const $=(q)=>document.querySelector(q);const $$=(q)=>Array.from(document.querySelectorAll(q));
const GROUPS='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
function read(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
const defaults={settings:{teamLimit:48,groupCount:8,qualifyPerGroup:2,teamsPerGroup:4,adminPin:'258079'},teams:[{id:1,name:'Team A',group:'A'},{id:2,name:'Team B',group:'A'},{id:3,name:'Team C',group:'A'},{id:4,name:'Team D',group:'A'},{id:5,name:'Team E',group:'B'},{id:6,name:'Team F',group:'B'},{id:7,name:'Team G',group:'B'},{id:8,name:'Team H',group:'B'}],matches:[{id:1,round:'Group Stage',group:'A',home:'Team A',away:'Team B',homeScore:'',awayScore:'',date:'2026-06-10',time:'16:00'},{id:2,round:'Group Stage',group:'A',home:'Team C',away:'Team D',homeScore:'',awayScore:'',date:'2026-06-10',time:'18:00'},{id:3,round:'Group Stage',group:'B',home:'Team E',away:'Team F',homeScore:'',awayScore:'',date:'2026-06-11',time:'16:00'},{id:4,round:'Group Stage',group:'B',home:'Team G',away:'Team H',homeScore:'',awayScore:'',date:'2026-06-11',time:'18:00'}]};
function data(){return {settings:read('efl_settings',defaults.settings),teams:read('efl_teams',defaults.teams),matches:read('efl_matches',defaults.matches)}}
function setData(o){if(o.settings)save('efl_settings',o.settings);if(o.teams)save('efl_teams',o.teams);if(o.matches)save('efl_matches',o.matches)}
function layout(active){return `<header class="top"><div class="wrap nav"><a class="brand" href="index.html"><img src="logo.png"><span>EFL</span></a><nav class="links"><a class="${active==='home'?'active':''}" href="index.html">Home</a><a class="${active==='fixtures'?'active':''}" href="fixtures.html">Fixtures</a><a class="${active==='results'?'active':''}" href="results.html">Results</a><a class="${active==='standings'?'active':''}" href="standings.html">Standings</a><a class="${active==='bracket'?'active':''}" href="bracket.html">Bracket</a><a class="${active==='teams'?'active':''}" href="teams.html">Teams</a><a class="admin-dot" title="Admin" href="admin.html">⚙</a></nav></div></header>`}
function init(active){document.body.insertAdjacentHTML('afterbegin',layout(active));document.body.insertAdjacentHTML('beforeend',`<footer class="footer"><div class="wrap">© ${new Date().getFullYear()} EFL Tournament</div></footer>`)}
function standings(){let {teams,matches}=data();let map={};teams.forEach(t=>map[t.name]={team:t.name,group:t.group,P:0,W:0,D:0,L:0,GF:0,GA:0,GD:0,Pts:0});matches.filter(m=>m.round==='Group Stage'&&m.homeScore!==''&&m.awayScore!=='').forEach(m=>{let h=map[m.home],a=map[m.away];if(!h||!a)return;let hs=+m.homeScore,as=+m.awayScore;h.P++;a.P++;h.GF+=hs;h.GA+=as;a.GF+=as;a.GA+=hs;h.GD=h.GF-h.GA;a.GD=a.GF-a.GA;if(hs>as){h.W++;a.L++;h.Pts+=3}else if(hs<as){a.W++;h.L++;a.Pts+=3}else{h.D++;a.D++;h.Pts++;a.Pts++}});return Object.values(map).sort((a,b)=>a.group.localeCompare(b.group)||b.Pts-a.Pts||b.GD-a.GD||b.GF-a.GF)}
function matchCard(m,editable=false){let score=(m.homeScore===''||m.awayScore==='')?'vs':`${m.homeScore} - ${m.awayScore}`;return `<div class="match"><div><b>${m.home}</b><div class="small">${m.date} • ${m.time} • ${m.group||m.round}</div><b>${m.away}</b></div><div class="score">${score}</div>${editable?`<button class="btn" onclick="editResult(${m.id})">Edit</button>`:''}</div>`}
function renderHome(){init('home');let {teams,matches,settings}=data();$('#app').innerHTML=`<section class="hero"><div class="wrap hero-grid"><div class="panel"><span class="tag">UCL Format Tournament</span><h1>Elite Football League</h1><p>Fixtures, results, group standings and knockout bracket in one clean football website.</p><a class="btn" href="fixtures.html">View Fixtures</a> <a class="btn alt" href="standings.html">View Standings</a><div class="stats"><div class="stat"><b>${teams.length}</b><br><span>Teams</span></div><div class="stat"><b>${settings.groupCount}</b><br><span>Groups</span></div><div class="stat"><b>${settings.qualifyPerGroup}</b><br><span>Qualify / Group</span></div></div></div><div class="panel"><h2>Upcoming Fixtures</h2>${matches.slice(0,4).map(m=>matchCard(m)).join('')}</div></div></section><section class="section"><div class="wrap"><div class="title"><h2>Latest Results</h2><a href="results.html">View all</a></div><div class="card">${matches.filter(m=>m.homeScore!==''&&m.awayScore!=='').slice(0,5).map(m=>matchCard(m)).join('')||'<p class="small">No results yet.</p>'}</div></div></section>`}
function renderFixtures(){init('fixtures');let ms=data().matches.filter(m=>m.homeScore===''||m.awayScore==='');$('#app').innerHTML=`<section class="section"><div class="wrap"><div class="title"><h2>Fixtures</h2></div><div class="card">${ms.map(m=>matchCard(m)).join('')||'No upcoming fixtures.'}</div></div></section>`}
function renderResults(){init('results');let ms=data().matches.filter(m=>m.homeScore!==''&&m.awayScore!=='');$('#app').innerHTML=`<section class="section"><div class="wrap"><div class="title"><h2>Results</h2></div><div class="card">${ms.map(m=>matchCard(m)).join('')||'No results yet.'}</div></div></section>`}
function renderTeams(){init('teams');let {teams}=data();$('#app').innerHTML=`<section class="section"><div class="wrap"><h2>Teams</h2><div class="grid">${teams.map(t=>`<div class="card"><h3>${t.name}</h3><span class="tag">Group ${t.group}</span></div>`).join('')}</div></div></section>`}
function renderStandings(){init('standings');let rows=standings();let groups=[...new Set(rows.map(r=>r.group))];$('#app').innerHTML=`<section class="section"><div class="wrap"><h2>Group Standings</h2>${groups.map(g=>`<h3 class="group-title">Group ${g}</h3><table class="table"><tr><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>Pts</th></tr>${rows.filter(r=>r.group===g).map(r=>`<tr><td><b>${r.team}</b></td><td>${r.P}</td><td>${r.W}</td><td>${r.D}</td><td>${r.L}</td><td>${r.GF}</td><td>${r.GA}</td><td>${r.GD}</td><td><b>${r.Pts}</b></td></tr>`).join('')}</table>`).join('')}</div></section>`}
function qualified(){let {settings}=data();let rows=standings();let out=[];GROUPS.slice(0,settings.groupCount).forEach(g=>out.push(...rows.filter(r=>r.group===g).slice(0,settings.qualifyPerGroup).map(r=>r.team)));return out}
function renderBracket(){init('bracket');let q=qualified();let rounds=['Qualified Teams','Round of 16','Quarter Finals','Semi Finals','Final'];$('#app').innerHTML=`<section class="section"><div class="wrap"><h2>Knockout Bracket</h2><p class="small">Bracket updates from group standings based on admin qualification settings.</p><div class="bracket">${rounds.map((r,i)=>`<div class="round"><h3>${r}</h3>${i===0?(q.map(t=>`<div class="slot">${t}</div>`).join('')||'<div class="slot">No qualified teams yet</div>'):'<div class="slot">To be generated</div><div class="slot">To be generated</div>'}</div>`).join('')}</div></div></section>`}
function renderAdmin(){init('');let logged=sessionStorage.getItem('efl_admin')==='yes';$('#app').innerHTML=logged?adminDash():loginBox();bindAdmin()}
function loginBox(){return `<section class="section"><div class="wrap"><div class="panel" style="max-width:420px;margin:auto"><h2>Admin Login</h2><div class="form"><input id="pin" type="password" placeholder="PIN"><button class="btn" id="loginBtn">Login</button><p class="small">Default PIN: 1234</p></div></div></div></section>`}
function adminDash(){let {settings,teams,matches}=data();return `<section class="section"><div class="wrap admin-layout"><div class="side panel"><button data-tab="settings" class="active">Tournament Settings</button><button data-tab="teams">Teams</button><button data-tab="fixtures">Fixtures</button><button data-tab="results">Edit Results</button><button onclick="sessionStorage.removeItem('efl_admin');location.reload()">Logout</button></div><div class="panel"><div id="adminContent"></div></div></div></section>`}
function bindAdmin(){let {settings}=data();let lb=$('#loginBtn');if(lb)lb.onclick=()=>{if($('#pin').value===data().settings.adminPin){sessionStorage.setItem('efl_admin','yes');location.reload()}else alert('Wrong PIN')};if($('#adminContent')){showAdminTab('settings');$$('.side button[data-tab]').forEach(b=>b.onclick=()=>{$$('.side button').forEach(x=>x.classList.remove('active'));b.classList.add('active');showAdminTab(b.dataset.tab)})}}
function showAdminTab(tab){let {settings,teams,matches}=data();let c=$('#adminContent');if(tab==='settings')c.innerHTML=`<h2>Tournament Settings</h2><div class="form"><label>Number of groups <input id="groupCount" type="number" min="1" max="12" value="${settings.groupCount}"></label><label>Teams per group <input id="teamsPerGroup" type="number" min="2" max="6" value="${settings.teamsPerGroup}"></label><label>Teams qualify per group <input id="qualifyPerGroup" type="number" min="1" max="6" value="${settings.qualifyPerGroup}"></label><label>Admin PIN <input id="adminPin" value="${settings.adminPin}"></label><button class="btn" onclick="saveSettings()">Save Settings</button></div>`;
if(tab==='teams')c.innerHTML=`<h2>Teams</h2><p class="small">Maximum 48 teams.</p><div class="form"><input id="teamName" placeholder="Team name"><select id="teamGroup">${GROUPS.slice(0,settings.groupCount).map(g=>`<option>${g}</option>`).join('')}</select><button class="btn" onclick="addTeam()">Add Team</button></div><br><table class="table"><tr><th>Team</th><th>Group</th><th>Action</th></tr>${teams.map(t=>`<tr><td><input value="${t.name}" onchange="updateTeam(${t.id},'name',this.value)"></td><td><select onchange="updateTeam(${t.id},'group',this.value)">${GROUPS.slice(0,settings.groupCount).map(g=>`<option ${t.group===g?'selected':''}>${g}</option>`).join('')}</select></td><td><button onclick="deleteTeam(${t.id})">Delete</button></td></tr>`).join('')}</table>`;
if(tab==='fixtures')c.innerHTML=`<h2>Fixtures</h2><button class="btn" onclick="generateFixtures()">Generate Group Fixtures</button><div class="card">${matches.map(m=>matchCard(m,false)).join('')}</div>`;
if(tab==='results')c.innerHTML=`<h2>Edit Results</h2><div class="card">${matches.map(m=>matchCard(m,true)).join('')}</div>`}
window.saveSettings=()=>{let s=data().settings;s.groupCount=+$('#groupCount').value;s.teamsPerGroup=+$('#teamsPerGroup').value;s.qualifyPerGroup=+$('#qualifyPerGroup').value;s.adminPin=$('#adminPin').value||'258079';setData({settings:s});alert('Saved');location.reload()}
window.addTeam=()=>{let d=data();if(d.teams.length>=48)return alert('Maximum 48 teams');let name=$('#teamName').value.trim();if(!name)return;d.teams.push({id:Date.now(),name,group:$('#teamGroup').value});setData({teams:d.teams});showAdminTab('teams')}
window.updateTeam=(id,k,v)=>{let d=data();d.teams=d.teams.map(t=>t.id===id?{...t,[k]:v}:t);setData({teams:d.teams})}
window.deleteTeam=(id)=>{let d=data();d.teams=d.teams.filter(t=>t.id!==id);setData({teams:d.teams});showAdminTab('teams')}
window.generateFixtures=()=>{let d=data();let ms=[];GROUPS.slice(0,d.settings.groupCount).forEach(g=>{let arr=d.teams.filter(t=>t.group===g);for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++)ms.push({id:Date.now()+ms.length,round:'Group Stage',group:g,home:arr[i].name,away:arr[j].name,homeScore:'',awayScore:'',date:'TBA',time:'TBA'})});d.matches=ms;setData({matches:ms});showAdminTab('fixtures')}
window.editResult=(id)=>{let d=data();let m=d.matches.find(x=>x.id===id);let hs=prompt(`${m.home} score`,m.homeScore);if(hs===null)return;let as=prompt(`${m.away} score`,m.awayScore);if(as===null)return;m.homeScore=hs;m.awayScore=as;setData({matches:d.matches});showAdminTab('results')}
